<?php

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-dashboard-addresses">
    <img src="<?php echo $this->getViewFileUrl('images/address.png'); ?>" alt="Address">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Address Book')) ?></strong>
    </div>
    <div class="block-content">
        <p class="block-content-text"><?= $block->escapeHtml(__('Edit address and your delivery preferences')) ?></p>
        <a class="action edit" href="<?= $block->escapeUrl($block->getAddressBookUrl()) ?>">
            <span><?= $block->escapeHtml(__('Manage Addresses')) ?></span>
        </a>
    </div>
</div>
