<?php

/** @var $block \Magento\Sales\Block\Order\Recent */
?>
<div class="block block-dashboard-orders">
    <img src="<?php echo $this->getViewFileUrl('images/order.png'); ?>" alt="Order">
    <div class="block-title order">
        <strong><?= $block->escapeHtml(__('My Orders')) ?></strong>
    </div>
    <div class="block-content">
        <p class="block-content-text"><?= $block->escapeHtml(__("Track your orders, return or buy items you've bought before")) ?></p>
        <a class="action view" href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
            <span><?= $block->escapeHtml(__('View My Orders')) ?></span>
        </a>
    </div>
</div>
